### ISSUE TITLE
Kerrekerud-reference to Ngermid song by Tres 

### ISSUE THREAD

**Issue by Gnalu** [tekinged/missing#374] opened 2022-10-23 03:20 UTC
Means our tree.

**Comment by ChrisPerrette** [comment] 2022-10-23 18:11
Is there another issue number this references?

**Comment by johnbent** [comment] 2022-10-23 18:21
Thanks @Gnalu !

However, our current database / webpage does not attempt to list every possible form of every word. 

This is the same decision that the original dictionary made. For nouns, to only list the unpossessed form (eg kerrekar) and the 3rd person singular form (eg kerrekerul). 

Maybe in the future, we will try to add more forms but right now it is just too hard because there are so so many forms. If I could program the system to automatically add them all, I'd be tempted to do that. But the problem is that there are exceptions to the rules so autopopulating will create some mistakes which would be really hard to find. 

Hmm, maybe in the future, I could create a dekaingeseu page that guesses at more forms and has a native speaker confirm them one at a time..

But for now, I'm closing this thread. 😃

**Closed as not planned** 2022-10-23 18:21 UTC

**Comment by Gnalu** [comment] 2022-10-23 19:28
Okay so we are practically done with missing words. Awesome!!!
